from backend.domain.exceptions import ActiveIndexNotReadyError
from backend.domain.exceptions import EmbeddingModelUnavailableError
from backend.domain.exceptions import PaperParseError
from backend.domain.exceptions import SessionNotFoundError
